DROP TABLE IF EXISTS issues;
DROP TABLE IF EXISTS issue_batches;
DROP TABLE IF EXISTS projects;
DROP TABLE IF EXISTS tasks;
DROP TABLE IF EXISTS prompts;
DROP TABLE IF EXISTS contexts;
DROP TABLE IF EXISTS providers;
DROP TABLE IF EXISTS users;